function skillsMember() {
    var data = {
        skills: {
            "java": 1,
            "python": 1,
            "c++": 1,
            "c": 1,
            "c#": 1,
            "php": 1,
            "javascript": 1,
            "html": 1,
            "css": 1,
            "sql": 1,
            "mysql": 1,
            "mongodb": 1,
            "nodejs": 1,
            "angularjs": 1,
            "reactjs": 1,
            "jquery": 1,
            "bootstrap": 1,
            "linux": 1,
            "windows": 1,
            "android": 1,
            "ios": 1,
            "laravel": 1,
            "spring": 1,
            "hibernate": 1,
            "android studio": 1,
            "eclipse": 1,
            "visual studio": 1,
            "netbeans": 1,
            "xcode": 1,
            "photoshop": 1,
            "illustrator": 1,
            "premiere": 1,
            "after effects": 1,
            "adobe xd": 1,
            "sketch": 1,
            "zeplin": 1,
            "invision": 1,
            "figma": 1,
            "corel draw": 1,
            "adobe premiere": 1,
            "adobe photoshop": 1,
            "adobe illustrator": 1,
            "adobe after effects": 1,
            "adobe xd": 1,
            "corel": 1,
            "corel draw": 1,
            "corel video studio": 1,
            "corel videostudio": 1,
            "corel paintshop pro": 1,
            "corel paint shop pro": 1,
            "corel photo paint": 1,
            "corel photo-paint": 1,
            "corel designer": 1,
            "corel painter": 1,
            "corel draw graphic suite": 1,
            "coreldraw graphic suite": 1,
            "corel draw graphics suite": 1,
            "coreldraw graphics suite": 1 
        }        
    };
    return data;    
}